
var Module = (() => {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var a;a||(a=typeof Module !== 'undefined' ? Module : {});var q,r;a.ready=new Promise(function(b,c){q=b;r=c});var v=Object.assign({},a),w="object"==typeof window,x="function"==typeof importScripts,y="",z,A,B,fs,C,D;
if("object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node)y=x?require("path").dirname(y)+"/":__dirname+"/",D=()=>{C||(fs=require("fs"),C=require("path"))},z=function(b,c){D();b=C.normalize(b);return fs.readFileSync(b,c?void 0:"utf8")},B=b=>{b=z(b,!0);b.buffer||(b=new Uint8Array(b));return b},A=(b,c,f)=>{D();b=C.normalize(b);fs.readFile(b,function(g,e){g?f(g):c(e.buffer)})},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),
process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",function(b){throw b;}),a.inspect=function(){return"[Emscripten Module object]"};else if(w||x)x?y=self.location.href:"undefined"!=typeof document&&document.currentScript&&(y=document.currentScript.src),_scriptDir&&(y=_scriptDir),0!==y.indexOf("blob:")?y=y.substr(0,y.replace(/[?#].*/,"").lastIndexOf("/")+1):y="",z=b=>{var c=new XMLHttpRequest;c.open("GET",b,!1);c.send(null);return c.responseText},x&&(B=b=>{var c=new XMLHttpRequest;
c.open("GET",b,!1);c.responseType="arraybuffer";c.send(null);return new Uint8Array(c.response)}),A=(b,c,f)=>{var g=new XMLHttpRequest;g.open("GET",b,!0);g.responseType="arraybuffer";g.onload=()=>{200==g.status||0==g.status&&g.response?c(g.response):f()};g.onerror=f;g.send(null)};a.print||console.log.bind(console);var F=a.printErr||console.warn.bind(console);Object.assign(a,v);v=null;var G;a.wasmBinary&&(G=a.wasmBinary);var noExitRuntime=a.noExitRuntime||!0;"object"!=typeof WebAssembly&&H("no native wasm support detected");
var I,J=!1;
function aa(b,c,f,g){var e={string:function(d){var n=0;if(null!==d&&void 0!==d&&0!==d){var m=(d.length<<2)+1;n=K(m);var k=n,h=L;if(0<m){m=k+m-1;for(var t=0;t<d.length;++t){var l=d.charCodeAt(t);if(55296<=l&&57343>=l){var ja=d.charCodeAt(++t);l=65536+((l&1023)<<10)|ja&1023}if(127>=l){if(k>=m)break;h[k++]=l}else{if(2047>=l){if(k+1>=m)break;h[k++]=192|l>>6}else{if(65535>=l){if(k+2>=m)break;h[k++]=224|l>>12}else{if(k+3>=m)break;h[k++]=240|l>>18;h[k++]=128|l>>12&63}h[k++]=128|l>>6&63}h[k++]=128|l&63}}h[k]=
0}}return n},array:function(d){var n=K(d.length);M.set(d,n);return n}};b=a["_"+b];var p=[],E=0;if(g)for(var u=0;u<g.length;u++){var V=e[f[u]];V?(0===E&&(E=N()),p[u]=V(g[u])):p[u]=g[u]}f=b.apply(null,p);return f=function(d){0!==E&&O(E);if("string"===c)if(d){for(var n=L,m=d+NaN,k=d;n[k]&&!(k>=m);)++k;if(16<k-d&&n.buffer&&P)d=P.decode(n.subarray(d,k));else{for(m="";d<k;){var h=n[d++];if(h&128){var t=n[d++]&63;if(192==(h&224))m+=String.fromCharCode((h&31)<<6|t);else{var l=n[d++]&63;h=224==(h&240)?(h&
15)<<12|t<<6|l:(h&7)<<18|t<<12|l<<6|n[d++]&63;65536>h?m+=String.fromCharCode(h):(h-=65536,m+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else m+=String.fromCharCode(h)}d=m}}else d="";else d="boolean"===c?!!d:d;return d}(f)}var P="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,M,L,Q,ba=[],ca=[],da=[];function ea(){var b=a.preRun.shift();ba.unshift(b)}var R=0,S=null,T=null;
function H(b){if(a.onAbort)a.onAbort(b);b="Aborted("+b+")";F(b);J=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");r(b);throw b;}function fa(){return U.startsWith("data:application/octet-stream;base64,")}var U;if(a.locateFile){if(U="lib.wasm",!fa()){var ha=U;U=a.locateFile?a.locateFile(ha,y):y+ha}}else U=(new URL("lib.wasm",import.meta.url)).toString();
function ia(){var b=U;try{if(b==U&&G)return new Uint8Array(G);if(B)return B(b);throw"both async and sync fetching of the wasm failed";}catch(c){H(c)}}
function ka(){if(!G&&(w||x)){if("function"==typeof fetch&&!U.startsWith("file://"))return fetch(U,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+U+"'";return b.arrayBuffer()}).catch(function(){return ia()});if(A)return new Promise(function(b,c){A(U,function(f){b(new Uint8Array(f))},c)})}return Promise.resolve().then(function(){return ia()})}
function W(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var f=c.l;"number"==typeof f?void 0===c.j?la(f)():la(f)(c.j):f(void 0===c.j?null:c.j)}}}var X=[];function la(b){var c=X[b];c||(b>=X.length&&(X.length=b+1),X[b]=c=Q.get(b));return c}var ma={b:function(){H("")},a:function(){H("OOM")}};
(function(){function b(e){a.asm=e.exports;I=a.asm.c;e=I.buffer;a.HEAP8=M=new Int8Array(e);a.HEAP16=new Int16Array(e);a.HEAP32=new Int32Array(e);a.HEAPU8=L=new Uint8Array(e);a.HEAPU16=new Uint16Array(e);a.HEAPU32=new Uint32Array(e);a.HEAPF32=new Float32Array(e);a.HEAPF64=new Float64Array(e);Q=a.asm.i;ca.unshift(a.asm.d);R--;a.monitorRunDependencies&&a.monitorRunDependencies(R);0==R&&(null!==S&&(clearInterval(S),S=null),T&&(e=T,T=null,e()))}function c(e){b(e.instance)}function f(e){return ka().then(function(p){return WebAssembly.instantiate(p,
g)}).then(function(p){return p}).then(e,function(p){F("failed to asynchronously prepare wasm: "+p);H(p)})}var g={a:ma};R++;a.monitorRunDependencies&&a.monitorRunDependencies(R);if(a.instantiateWasm)try{return a.instantiateWasm(g,b)}catch(e){return F("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return G||"function"!=typeof WebAssembly.instantiateStreaming||fa()||U.startsWith("file://")||"function"!=typeof fetch?f(c):fetch(U,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
g).then(c,function(p){F("wasm streaming compile failed: "+p);F("falling back to ArrayBuffer instantiation");return f(c)})})})().catch(r);return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.d).apply(null,arguments)};a._calculateNetwork=function(){return(a._calculateNetwork=a.asm.e).apply(null,arguments)};
var N=a.stackSave=function(){return(N=a.stackSave=a.asm.f).apply(null,arguments)},O=a.stackRestore=function(){return(O=a.stackRestore=a.asm.g).apply(null,arguments)},K=a.stackAlloc=function(){return(K=a.stackAlloc=a.asm.h).apply(null,arguments)};a.cwrap=function(b,c,f,g){f=f||[];var e=f.every(function(p){return"number"===p});return"string"!==c&&e&&!g?a["_"+b]:function(){return aa(b,c,f,arguments)}};var Y;T=function na(){Y||Z();Y||(T=na)};
function Z(){function b(){if(!Y&&(Y=!0,a.calledRun=!0,!J)){W(ca);q(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();da.unshift(c)}W(da)}}if(!(0<R)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)ea();W(ba);0<R||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=Z;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();Z();


  return Module.ready
}
);
})();
export default Module;